name: Build (CI)

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    permissions:
      contents: read
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Labeler
        uses: actions/labeler@v5.0.0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            wrapper

      - name: Make sure gradlew is executable
        run: "chmod +x ./gradlew"

      - name: Build project
        run: "./gradlew build"

      - name: Execute tests
        run: "./gradlew test"

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: JARs
          path: links-detektor/build/libs/*.jar

# TODO: Add automation for auto artifactory push
