name: Build Master & Publish

on:
  push:
    branches:
      - master

jobs:
  build-master:
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version to env
        run: echo "VERSION=$(echo ${{steps.release_drafter.outputs.tag_name}})" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Make sure gradlew is executable
        run: "chmod +x ./gradlew"

      - name: Build project
        run: "VERSION=${{steps.release_drafter.outputs.tag_name}} ./gradlew build"

      - name: Execute tests
        run: "./gradlew test"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: JARs
          path: links-detektor/build/libs/*.jar

      - name: Upload Assets to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }}
          asset_path: links-detektor/build/libs/*.jar
          github_token: ${{ secrets.GITHUB_TOKEN }}
